version: '3'
services:
  
  #PHP Service
  goservice:
    build:
      context: ./source
      dockerfile: ./../Dockerfile
    container_name: goservice
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: goservice
      SERVICE_TAGS: dev
    networks:
      - app-network

  #Nginx Service
  nginx:
    build: "./nginx"
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  #MySQL Service
  db:
    image: mysql
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local